### ISSUE TITLE
Next.js 9.5 Webpack v5 support incompatible with @prefresh/next plugin

### ISSUE THREAD

**Issue by GavinRay97** [JoviDeCroock/prefresh#136]
Just wanted to leave a friendly heads up, attempted to upgrade today for better build times and got this error:

```sh
❯ yarn dev
yarn run v1.22.4
warning package.json: No license field
$ next
ready - started server on http://localhost:3000
(node:23923) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:23923) [DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE] DeprecationWarning: MainTemplate.hooks.require is deprecated (use JavascriptModulesPlugin.getCompilationHooks().renderRequire instead)
(node:23923) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
/home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/NormalModuleFactory.js:249
                                                        throw new Error(deprecationChangedHookMessage("afterResolve"));
                                                        ^

Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
```

Running with `node --trace-deprecation ./node_modules/next/dist/bin/next` gives better error, and points to the exact bit of code:

```sh
❯ node --trace-deprecation ./node_modules/next/dist/bin/next
ready - started server on http://localhost:3000
(node:27700) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
    at /home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/config/normalization.js:201:9
    at nestedConfig (/home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/config/normalization.js:42:52)
    at getNormalizedWebpackOptions (/home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/config/normalization.js:180:17)
    at createCompiler (/home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/webpack.js:58:18)
    at /home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/webpack.js:40:48
    at Array.map (<anonymous>)
    at createMultiCompiler (/home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/webpack.js:40:33)
    at webpack (/home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/webpack.js:108:14)
    at f (/home/user/Projects/hasura-admin-next-preact/node_modules/webpack/lib/index.js:31:15)
    at HotReloader.start (/home/user/Projects/hasura-admin-next-preact/node_modules/next/dist/server/hot-reloader.js:16:415)
(node:27700) [DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE] DeprecationWarning: MainTemplate.hooks.require is deprecated (use JavascriptModulesPlugin.getCompilationHooks().renderRequire instead)
    at /home/user/Projects/hasura-admin-next-preact/node_modules/@prefresh/next/src/plugin.js:46:43
```

Seems like this is the bit it's complaining about being deprecated (`@prefresh/next/src/plugin.js:46:43`):
```js
compiler.hooks.compilation.tap(NAME, compilation => {
	compilation.mainTemplate.hooks.require.tap(NAME, (source, chunk, hash) =>
		createRefreshTemplate(source, chunk, hash, compilation.mainTemplate)
	);
});
```

> DeprecationWarning: MainTemplate.hooks.require is deprecated (use JavascriptModulesPlugin.getCompilationHooks().renderRequire instead)
    at /home/user/Projects/hasura-admin-next-preact/node_modules/@prefresh/next/src/plugin.js:46:43

**Comment by JoviDeCroock** [comment]
Yea, it’s on the V1 roadmap to support both v4 and v5. Don’t have experience with v5 yet but making time this weekend.

**Comment by GavinRay97** [comment]
Ah my mistake for not looking. Appreciate the response!

**Comment by JoviDeCroock** [comment]
@GavinRay97 made a PR that adds this functionality, still need to test it extensively but I have faith in it 😅 will try and get this done by this weekend.

**Comment by GavinRay97** [comment]
@JoviDeCroock Saw you merged the changes into main, amazing! I just pulled and tested, looks like everything is good :tada: 

![prefresh-upgrade-working](https://user-images.githubusercontent.com/26604994/89478609-79e26800-d75e-11ea-8d44-a5ec87a4d6f6.gif)

For reproducibility's sake and anyone else who might read:

```json
  "dependencies": {
    "@prefresh/next": "^0.3.2",
    "next": "^9.5.2-canary.8",
    "preact": "^10.4.7",
    "preact-render-to-string": "^5.1.10",
    "prefresh": "JoviDeCroock/prefresh",
    "react": "github:preact-compat/react#1.0.0",
    "react-dom": "github:preact-compat/react-dom#1.0.0",
    "react-ssr-prepass": "npm:preact-ssr-prepass@^1.0.1"
  },
  "resolutions": {
    "webpack": "^5.0.0-beta.24"
  }
```

**Comment by GavinRay97** [comment]
One small bug that seems to have popped up (and maybe the code was broken to begin with but somehow was able to compile before) is that 80% of the time, a global store object I make will somehow be `null`, even if working a second before:

```ts
import React from 'react'
import { useLocalStore } from 'mobx-react-lite'

export const Store = {
  tables: [],
}

const storeContext = React.createContext<typeof Store | null>(null)

export const StoreProvider = ({ store, children }) => {
  const value = useLocalStore(() => store)
  return React.createElement(storeContext.Provider, { value, children })
  //return <storeContext.Provider value={store}>{children}</storeContext.Provider>
}

export const useStore = () => {
  const store = React.useContext(storeContext)
  if (!store) {
    // this is especially useful in TypeScript so you don't need to be checking for null all the time
    throw new Error('useStore must be used within a StoreProvider.')
  }
  return store
}
```

This `StoreProvider` is the topmost wrapping app component, and the `Store` object it reads from is declared directly next to the code so I'm really confused how it could ever be `null`:

```tsx
import { StoreProvider, Store } from '../store/mobx'

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <StoreProvider store={Store}>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </StoreProvider>
  )
}
```

![working-then-broken-preact-webpack](https://user-images.githubusercontent.com/26604994/89479660-5836b000-d761-11ea-90c2-22cd70c1f769.png)
