### ISSUE TITLE
@prefresh/next + next dev mode + webpack@5 = "TypeError: Cannot read property 'tap' of undefined"

### ISSUE THREAD

**Issue by 4cm4k1** [JoviDeCroock/prefresh#147]
Hi! 👋 

I was excited to try out Webpack 5 support with Next.js and Preact. It mostly works great! However, when in dev mode (`next dev` or `vc dev`), something goes awry:

```shell
TypeError: Cannot read property 'tap' of undefined
    at /Users/4cm4k1/Code/personal-website/node_modules/@prefresh/next/src/plugin.js:57:57
    at SyncHook.eval [as call] (eval at create (/Users/4cm4k1/Code/personal-website/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/4cm4k1/Code/personal-website/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/4cm4k1/Code/personal-website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/4cm4k1/Code/personal-website/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/4cm4k1/Code/personal-website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/4cm4k1/Code/personal-website/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Watching.js:41:32)
    at /Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Compiler.js:529:11)
    at new Watching (/Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Watching.js:30:17)
    at Compiler.watch (/Users/4cm4k1/Code/personal-website/node_modules/next/node_modules/webpack/lib/Compiler.js:244:10)
```

I have tried to track down why this is happening (or if this has been reported anywhere), but I have so far been unsuccessful. To be clear, this isn't a blocking issue, and it only occurs when:
- `@prefresh/next@latest`
- `next@canary` `dev` command
- `webpack@5`

My repo: https://github.com/4cm4k1/personal-website

Any thoughts? Thanks! 😄

**Comment by JoviDeCroock** [comment]
Hey,

The repo you are linking isn't using webpack 5, however I tried this myself with [`beta.22`](https://github.com/JoviDeCroock/prefresh/blob/main/packages/next/example/package.json#L14) which seemed to work fine. I'll need to now the version.

**Comment by 4cm4k1** [comment]
Right, I didn't update my repo to resolve to Webpack 5 because of the issues I was having locally. Behavior is also different depending on whether Webpack is a `devDependency` or `resolution`, and some of the presenting issues seem specific to Next.js support for Webpack 5. I tried with `beta.22` and `beta.26`. I'm not really sure what's going on, but for now I will close this issue and revisit it when Webpack 5 enters release candidate or final status. Thank you!

**Comment by JoviDeCroock** [comment]
No problem, glad to help out when I can @4cm4k1

**Comment by 4cm4k1** [comment]
I wanted to come back and note that setting a resolution for `tapable` to `^2.0.0-beta.11` (which is what `webpack@5` uses) resolves this issue that I had.
