### ISSUE TITLE
Next 10.0.6+ Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by tbgse** [JoviDeCroock/prefresh#274]
Hi, 

We're currently running into an issue with the latest versions of Next (10.0.6 / 10.0.7) where prefresh seems to complain about the webpack module missing. This seems to be due to a recent change with Next, as discussed here:
https://github.com/vercel/next.js/issues/21679
https://github.com/preactjs/next-plugin-preact/issues/18

We were waiting until 10.0.7 to raise an issue because it seemed like the Next team was working on fixing the issue in the latest release, but our builds are still failing. 

Here is the full error during our build on Vercel:

```
09:05:05.680 | > Build error occurred
-- | --
09:05:05.682 | Error: Cannot find module 'webpack'
09:05:05.682 | Require stack:
09:05:05.682 | - /vercel/workpath0/node_modules/@prefresh/webpack/src/index.js
09:05:05.682 | - /vercel/workpath0/node_modules/next-plugin-preact/node_modules/@prefresh/next/src/index.js
09:05:05.682 | - /vercel/workpath0/node_modules/next-plugin-preact/index.js
09:05:05.682 | - /vercel/workpath0/next.config.__vercel_builder_backup__.js
09:05:05.682 | - /vercel/workpath0/next.config.js
09:05:05.682 | - /vercel/workpath0/node_modules/next/dist/next-server/server/config.js
09:05:05.682 | - /vercel/workpath0/node_modules/next/dist/build/index.js
09:05:05.682 | - /vercel/workpath0/node_modules/next/dist/cli/next-build.js
09:05:05.682 | - /vercel/workpath0/node_modules/next/dist/bin/next
09:05:05.682 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
09:05:05.682 | at Function.Module._resolveFilename (/vercel/workpath0/node_modules/module-alias/index.js:49:29)
09:05:05.682 | at Function.Module._load (internal/modules/cjs/loader.js:667:27)
09:05:05.682 | at Module.require (internal/modules/cjs/loader.js:887:19)
09:05:05.682 | at require (internal/modules/cjs/helpers.js:74:18)
09:05:05.682 | at Object.<anonymous> (/vercel/workpath0/node_modules/@prefresh/webpack/src/index.js:1:17)
09:05:05.682 | at Module._compile (internal/modules/cjs/loader.js:999:30)
09:05:05.682 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
09:05:05.682 | at Module.load (internal/modules/cjs/loader.js:863:32)
09:05:05.683 | at Function.Module._load (internal/modules/cjs/loader.js:708:14)
09:05:05.683 | at Module.require (internal/modules/cjs/loader.js:887:19)
09:05:05.683 | at require (internal/modules/cjs/helpers.js:74:18)
09:05:05.683 | at Object.<anonymous> (/vercel/workpath0/node_modules/next-plugin-preact/node_modules/@prefresh/next/src/index.js:1:18)
09:05:05.683 | at Module._compile (internal/modules/cjs/loader.js:999:30)
09:05:05.683 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
09:05:05.683 | at Module.load (internal/modules/cjs/loader.js:863:32) {
09:05:05.683 | code: 'MODULE_NOT_FOUND',
09:05:05.683 | requireStack: [
09:05:05.683 | '/vercel/workpath0/node_modules/@prefresh/webpack/src/index.js',
09:05:05.683 | '/vercel/workpath0/node_modules/next-plugin-preact/node_modules/@prefresh/next/src/index.js',
09:05:05.683 | '/vercel/workpath0/node_modules/next-plugin-preact/index.js',
09:05:05.683 | '/vercel/workpath0/next.config.__vercel_builder_backup__.js',
09:05:05.683 | '/vercel/workpath0/next.config.js',
09:05:05.683 | '/vercel/workpath0/node_modules/next/dist/next-server/server/config.js',
09:05:05.683 | '/vercel/workpath0/node_modules/next/dist/build/index.js',
09:05:05.683 | '/vercel/workpath0/node_modules/next/dist/cli/next-build.js',
09:05:05.683 | '/vercel/workpath0/node_modules/next/dist/bin/next'
09:05:05.683 | ]
09:05:05.683 | }
```

Please let me know if there is anything I can do to help debug this further.

**Comment by JoviDeCroock** [comment]
Hey @tbgse 

This has been on my radar since the issue was raised in `next-plugin-preact`, however this isn't as easy as it sounds. Next bundles in both a version of webpack 4 and 5 now we'll probably have to split out the next plugin to not use `@prefresh/webpack` under the hood and even then we can't access the `webpack` dependencies from within a `loader` which starts making stuff considerably harder to manage.

I'm trying to come up with a reasonable solution while following the conversations going on on the Next side.

**Comment by tbgse** [comment]
Awesome, thanks for the quick response. Really boggles my mind that a "minor" version change of Next suddenly breaks compat with a ton of plugins. Really hope there will be a way forward that won't require too much work for plugin maintainers. 

I'll keep an eye on the conversations in `next-plugin-preact` and next itself as well, to see where this is going.

**Comment by JoviDeCroock** [comment]
I guess one of the possible solutions would be to set the `future.webpack5: true` option on and require webpack 5 as a dependency/peerDependency to Prefresh/next. WDYT?

**Comment by tbgse** [comment]
I think that sounds like the right path forward, seems like the next team wants to move everyone over to webpack 5 in the long term too 👍

**Comment by tbgse** [comment]
Hi @JoviDeCroock i finally have time this week to upgrade our next version and move towards webpack 5. Unfortunately I'm running into more issues, with webpack 5 the error has changed to the following:

```
Error: Cannot find module 'webpack/lib/dependencies/ConstDependency'
Require stack:
- /home/tbgse/dev/webpack-5-test/node_modules/@prefresh/webpack/src/index.js
- /home/tbgse/dev/webpack-5-test/node_modules/@prefresh/next/src/index.js
- /home/tbgse/dev/webpack-5-test/node_modules/next-plugin-preact/index.js
- /home/tbgse/dev/webpack-5-test/next.config.js
- /home/tbgse/dev/webpack-5-test/node_modules/next/dist/next-server/server/config.js
- /home/tbgse/dev/webpack-5-test/node_modules/next/dist/next-server/server/next-server.js
- /home/tbgse/dev/webpack-5-test/node_modules/next/dist/server/next.js
- /home/tbgse/dev/webpack-5-test/node_modules/next/dist/server/lib/start-server.js
- /home/tbgse/dev/webpack-5-test/node_modules/next/dist/cli/next-dev.js
- /home/tbgse/dev/webpack-5-test/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loade
```

I was able to reproduce this in a fresh next repo with three steps

1. run `npx create-next-app`
2. install `next-plugin-preact` with all additional deps
3. change next.config.js to the following:

```
const withPreact = require('next-plugin-preact');

module.exports = module.exports = withPreact({
  future: {
    webpack5: true,
  },
  webpack: function (config, options) {
    return config;
  },
});
```

Any idea if there is something i'm doing wrong here?
