### ISSUE TITLE
TypeError: Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by Esugenos** [JoviDeCroock/prefresh#276]
### Error
I was trying [your example](https://github.com/JoviDeCroock/prefresh/tree/main/packages/next/example), using this `package.json` (1)
```json
{
  "name": "nextjs-preact-demo",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build && next export -o build",
    "start": "NODE_ENV=production next start"
  },
  "devDependencies": {
    "@prefresh/next": "1.4.4"
  },
  "dependencies": {
    "@prefresh/webpack": "3.0.1",
    "next": "^9.5.4",
    "preact": "^10.5.7",
    "preact-render-to-string": "^5.1.4",
    "react": "npm:@preact/compat",
    "react-dom": "npm:@preact/compat",
    "react-ssr-prepass": "npm:preact-ssr-prepass@^1.0.1",
    "webpack": "^5.0.0-beta.22"
  },
  "license": "MIT"
}
```
And then `npm run dev` throws the following error:
```
> nextjs-preact-demo@1.0.0 dev
> next

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

ready - started server on http://localhost:3000
TypeError: Cannot read property 'tap' of undefined
    at E:\projects\js\hell\example\node_modules\@prefresh\webpack\src\index.js:78:61
    at SyncHook.eval [as call] (eval at create (E:\projects\js\hell\example\node_modules\next\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (E:\projects\js\hell\example\node_modules\next\node_modules\tapable\lib\Hook.js:154:20)
npx browserslist@latest --update-db
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

ready - started server on http://localhost:3000
TypeError: Cannot read property 'tap' of undefined
    at E:\projects\js\hell\example\node_modules\@prefresh\webpack\src\index.js:78:61
    at SyncHook.eval [as call] (eval at create (E:\projects\js\hell\example\node_modules\next\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (E:\projects\js\hell\example\node_modules\next\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (E:\projects\js\hell\example\node_modules\next\node_modules\webpack\lib\Compiler.js:631:26)
    at E:\projects\js\hell\example\node_modules\next\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\projects\js\hell\example\node_modules\next\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (E:\projects\js\hell\example\node_modules\next\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (E:\projects\js\hell\example\node_modules\next\node_modules\webpack\lib\Compiler.js:662:28)
    at E:\projects\js\hell\example\node_modules\next\node_modules\webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\projects\js\hell\example\node_modules\next\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
npm ERR! code 1
npm ERR! path E:\projects\js\hell\example
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c next
```
### Reproduction
Clone [your example](https://github.com/JoviDeCroock/prefresh/tree/main/packages/next/example)
Replace the existing `package.json` by (1)
Run `npm i`
Run `npm run dev`

### Spec
Windows 10
npm v7.5.4
____
Now it's been 2 days that I've been trying to find the right config to run nextjs + preact (with hooks) + hot-reloading.
What a pain. Anyway. 💩 Am I doing something wrong? Am I using the wrong versions?
Thank you in advance for your help

**Comment by JoviDeCroock** [comment]
Hey,

I'm sorry you're experiencing issues, your best bet would be to go to [`next-plugin-preact`](https://github.com/preactjs/next-plugin-preact) and follow their instructions up to next 10.0.5 I'm sure we have good support. Have to check after :)

**Comment by Esugenos** [comment]
Ahaha thanks @JoviDeCroock for your quick reply! Unfortunately I've already tried [`next-plugin-preact`](https://github.com/preactjs/next-plugin-preact) and had a similar error.

Running `npm run i` `npm run dev` in [`next-plugin-preact` demo ](https://github.com/preactjs/next-plugin-preact/tree/master/packages/demo) (as is, without any change) gives:
```
> next-plugin-preact-app@0.0.0 dev
> next

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ready - started server on http://localhost:3000
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
TypeError: Cannot read property 'context' of undefined
    at exports.useContext (E:\projects\js\next-plugin-preact-app\node_modules\preact\hooks\dist\hooks.js:1:2405)
    at Html (E:\projects\js\next-plugin-preact-app\.next\server\pages\_document.js:330:29)
    at processChild (E:\projects\js\next-plugin-preact-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (E:\projects\js\next-plugin-preact-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (E:\projects\js\next-plugin-preact-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (E:\projects\js\next-plugin-preact-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToStaticMarkup (E:\projects\js\next-plugin-preact-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:4004:27)
    at renderDocument (E:\projects\js\next-plugin-preact-app\node_modules\next\dist\next-server\server\render.js:3:669)
    at renderToHTML (E:\projects\js\next-plugin-preact-app\node_modules\next\dist\next-server\server\render.js:52:103)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
event - build page: /next/dist/pages/_error
```

**Comment by JoviDeCroock** [comment]
Made an example for you @Esugenos https://github.com/JoviDeCroock/next-demo

**Comment by Esugenos** [comment]
Thank you so much for the example 😍
I just cloned it, `npm i` `npm run build` -> works 👌 but `npm run dev` -> same error:
```
> next-preact-demo@0.0.0 dev
> next

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ready - started server on http://localhost:3000
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
TypeError: Cannot read property 'context' of undefined
    at exports.useContext (E:\projects\js\next-demo-master\node_modules\preact\hooks\dist\hooks.js:1:2405)
    at Html (E:\projects\js\next-demo-master\.next\server\pages\_document.js:324:29)
    at processChild (E:\projects\js\next-demo-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\projects\js\next-demo-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\projects\js\next-demo-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\projects\js\next-demo-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (E:\projects\js\next-demo-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at renderDocument (E:\projects\js\next-demo-master\node_modules\next\dist\next-server\server\render.js:3:696)
    at renderToHTML (E:\projects\js\next-demo-master\node_modules\next\dist\next-server\server\render.js:56:103)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async E:\projects\js\next-demo-master\node_modules\next\dist\next-server\server\next-server.js:107:97
    at async E:\projects\js\next-demo-master\node_modules\next\dist\next-server\server\next-server.js:100:142
    at async DevServer.renderToHTMLWithComponents (E:\projects\js\next-demo-master\node_modules\next\dist\next-server\server\next-server.js:132:387)
    at async DevServer.renderToHTML (E:\projects\js\next-demo-master\node_modules\next\dist\next-server\server\next-server.js:133:522)
    at async DevServer.renderToHTML (E:\projects\js\next-demo-master\node_modules\next\dist\server\next-dev-server.js:34:578)
    at async DevServer.render (E:\projects\js\next-demo-master\node_modules\next\dist\next-server\server\next-server.js:72:236)
event - build page: /next/dist/pages/_error
```
Is your example working for you? very weird, I also tried to clear my npm cache (just in case), no effect.
Do you also have these 7 vulnerabilities at the beginning? (3 low, 4 high)
🤔

**Comment by JoviDeCroock** [comment]
I install the deps with yarn but apart from that I do the same thing.

**Comment by TsumiNa** [comment]
Add webpack 4.x.x as devDependencies will resolve this error

**Comment by JoviDeCroock** [comment]
Will close this as we've got a resolution, there is another issue open for a known issue with Next (missing webpack dep) this starts at 10.0.6

**Comment by geisterfurz007** [comment]
I hit the same error as @Esugenos (about context) in a monorepo setup with Storybook in a sibling package. I believe it's because of some hoisted package but I have spent several evenings trying to figure out which one it is and failed miserably. I am both on next@10.0.5 and webpack@4.46.0. I also tried to nohoist several packages I thought might be picked up from the storybook dependencies with no luck so far.

If there is a reliable way to tell which might be the culprit here, I would be extremely happy to know, thanks!

**Comment by JoviDeCroock** [comment]
Hmm, this issue only occurs if you're running Webpack 5 normally as this is the code-path in question https://github.com/JoviDeCroock/prefresh/blob/main/packages/webpack/src/index.js#L78 it occurs when you use one of the Next versions that bundles in Webpack.

I've yet to find a good solution for this but afaik they're working on it on the Next side as wel

**Comment by geisterfurz007** [comment]
Oops, I am not sure if I was clear enough with what I meant. I don't hit the "original" `Cannot read property 'tap' of undefined` but the one mentioned [here](https://github.com/JoviDeCroock/prefresh/issues/276#issuecomment-780947157). I can open a new issue for that though for better tracking if that helps.

I also plan to go through all storybook dependencies one by one this evening to try and find the one causing issues.

**Comment by geisterfurz007** [comment]
Just as an update; this occurs between very wild package resolution which are not caused by this package. Storybook declares react and react-dom as dependencies which seem to be picked up by next for some reason. If I no-hoist both those packages, next doesn't start anymore because it cannot find react which for no reason is in packages/web/node_modules instead of node_modules where react-dom sits. Either way this appears to be an issue with Yarn or Next or not sure what and not this plugin :)

If I finally figure out how to set things up so that next and storybook work next to each other, I will update this post to maybe help someone in the future (or be able to look it up myself).

**Comment by JoviDeCroock** [comment]
Hey @geisterfurz007 very much appreciated, I also worked on an error message when we are working with differing versions of webpack :)
