### ISSUE TITLE
Uncaught TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by ombene** [JoviDeCroock/prefresh#295]
Summary
---

The error I'm seeing, in the browser console ([using this modified webpack example](https://github.com/ombene/prefresh/tree/demo-string-component-error/packages/webpack/example)):

```
Uncaught TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at Object.register (index.js:163)
    at self.$RefreshReg$ (main.js:1082)
    at eval (CustomAnchor.js:18)
    at ./src/CustomAnchor.js (main.js:160)
    at Module.options.factory (main.js:1087)
    at __webpack_require__ (main.js:552)
    at fn (main.js:762)
    at eval (App.js:6)
    at ./src/App.js (main.js:149)
```

And the browser page is just blank.

The problem seems to arise when a variable with a capital letter is passed to a function call and the result captured in another variable with a capital letter, and exported, when the value of the latter variable is a primitive (as in, an invalid `WeakMap` key):

```js
const identity = (value) => value;
const Foo = 5;
const Bar = identity(Foo);
export default Bar;
```

Reproducible case
---

I made a branch showing the problem specifically for the webpack example in this repo's source code, relevant diff here: https://github.com/ombene/prefresh/compare/main...demo-string-component-error.

I did a first pass of adding a test case, relevant diff here: https://github.com/ombene/prefresh/compare/main...373a4335db3d2f4eab4569862ccd0e8f19e9f480. I expected the problem to be general across all integrations (and as I'll mention later, this is happening for me in a next JS project), but at the moment at least, some integrations appear to succeed.

<details>
<summary>
Result of my local test run for commit https://github.com/ombene/prefresh/commit/373a4335db3d2f4eab4569862ccd0e8f19e9f480 
</summary>

```
 FAIL  test/index.test.js (242.002 s)
  Prefresh integrations
    vite
      ✓ basic component (1030 ms)
      ✓ add export (1011 ms)
      ✓ add file and import it (4020 ms)
      ✓ custom hook (2070 ms)
      ✓ resets hook state (1012 ms)
      ✓ re-runs changed effects (1015 ms)
      ✓ works for class-components (1012 ms)
      ✕ add a string-component file using a higher-order component (3063 ms)
      ✓ can change methods (1026 ms)
      ✓ can hot reload context (1041 ms)
    snowpack
      ✓ basic component (1032 ms)
      ✓ add export (1015 ms)
      ✓ add file and import it (4020 ms)
      ✓ custom hook (2055 ms)
      ✓ resets hook state (1011 ms)
      ✓ re-runs changed effects (1014 ms)
      ✓ works for class-components (1007 ms)
      ✕ add a string-component file using a higher-order component (3046 ms)
      ✓ can change methods (1019 ms)
      ✓ can hot reload context (1045 ms)
    nollup
      ✓ basic component (1022 ms)
      ✓ add export (1008 ms)
      ✓ add file and import it (4020 ms)
      ✓ custom hook (2054 ms)
      ✓ resets hook state (1007 ms)
      ✓ re-runs changed effects (1010 ms)
      ✓ works for class-components (1013 ms)
      ✕ add a string-component file using a higher-order component (3054 ms)
      ✓ can change methods (1030 ms)
      ✓ can hot reload context (1031 ms)
    next
      ✓ basic component (1011 ms)
      ✓ add export (1013 ms)
      ✓ add file and import it (4019 ms)
      ✓ custom hook (2048 ms)
      ✓ resets hook state (1009 ms)
      ✓ re-runs changed effects (1011 ms)
      ✓ works for class-components (1011 ms)
      ✓ add a string-component file using a higher-order component (4027 ms)
      ✕ can change methods (1053 ms)
      ✕ can hot reload context (26 ms)
      ✕ can hot reload externally defined JSX (10 ms)
    webpack
      ✓ basic component (1020 ms)
      ✓ add export (1010 ms)
      ✓ add file and import it (4023 ms)
      ✓ custom hook (2050 ms)
      ✓ resets hook state (1009 ms)
      ✓ re-runs changed effects (1012 ms)
      ✓ works for class-components (1010 ms)
      ✕ add a string-component file using a higher-order component (3051 ms)
      ✓ can change methods (1022 ms)
      ✓ can hot reload context (1043 ms)
      ✕ can hot reload externally defined JSX (1013 ms)
    web-dev-server
      ✓ basic component (1027 ms)
      ✓ add export (1012 ms)
      ✓ add file and import it (4016 ms)
      ✓ custom hook (2051 ms)
      ✓ resets hook state (1008 ms)
      ✓ re-runs changed effects (1011 ms)
      ✓ works for class-components (1009 ms)
      ✕ add a string-component file using a higher-order component (3052 ms)
      ✓ can change methods (1020 ms)
      ✓ can hot reload context (1049 ms)
    next-webpack5
      ✓ basic component (1015 ms)
      ✓ add export (1007 ms)
      ✓ custom hook (2072 ms)
      ✓ resets hook state (1011 ms)
      ✓ re-runs changed effects (1009 ms)
      ✓ works for class-components (1011 ms)
      ✓ add a string-component file using a higher-order component (4022 ms)
      ✕ can change methods (1080 ms)
      ✕ can hot reload context (13 ms)

  ● Prefresh integrations › vite › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "SPAN"
    Received string:    ""

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
      at Object.<anonymous> (test/index.test.js:276:9)

  ● Prefresh integrations › snowpack › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "SPAN"
    Received string:    ""

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
      at Object.<anonymous> (test/index.test.js:276:9)

  ● Prefresh integrations › nollup › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "SPAN"
    Received string:    ""

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
      at Object.<anonymous> (test/index.test.js:276:9)

  ● Prefresh integrations › next › can change methods

    expect(received).toMatch(expected)

    Expected substring: "bye"
    Received string:    "hi"

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/index.test.js:295:9)

  ● Prefresh integrations › next › can hot reload context

    expect(received).toMatch(expected)

    Matcher error: received value must be a string

    Received has value: null

      314 |         const storeItems = await page.$('.store-items');
      315 |         let children = await storeItems.$$('li');
    > 316 |         expect(await getText(children[0])).toMatch('apple');
          |                                            ^
      317 | 
      318 |         await updateFile('src/context.jsx', content =>
      319 |           content.replace(

      at Object.<anonymous> (test/index.test.js:316:44)
          at runMicrotasks (<anonymous>)

  ● Prefresh integrations › next › can hot reload externally defined JSX

    expect(received).toBe(expected) // Object.is equality

    Expected: "rgb(0, 0, 0)"
    Received: "rgba(0, 0, 0, 0)"

      340 |           expect(
      341 |             await page.$eval('#color', e => getComputedStyle(e).backgroundColor)
    > 342 |           ).toBe('rgb(0, 0, 0)');
          |             ^
      343 | 
      344 |           await updateFile('src/styles.js', content =>
      345 |             content.replace(

      at Object.<anonymous> (test/index.test.js:342:13)
          at runMicrotasks (<anonymous>)

  ● Prefresh integrations › webpack › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "SPAN"
    Received string:    ""

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/index.test.js:276:9)

  ● Prefresh integrations › webpack › can hot reload externally defined JSX

    expect(received).toBe(expected) // Object.is equality

    Expected: "rgb(255, 255, 255)"
    Received: "rgb(0, 0, 0)"

      352 |           expect(
      353 |             await page.$eval('#color', e => getComputedStyle(e).backgroundColor)
    > 354 |           ).toBe('rgb(255, 255, 255)');
          |             ^
      355 |         });
      356 |       }
      357 |     });

      at Object.<anonymous> (test/index.test.js:354:13)
          at runMicrotasks (<anonymous>)

  ● Prefresh integrations › web-dev-server › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "SPAN"
    Received string:    ""

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/index.test.js:276:9)

  ● Prefresh integrations › next-webpack5 › can change methods

    expect(received).toMatch(expected)

    Expected substring: "bye"
    Received string:    "hi"

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/index.test.js:295:9)

  ● Prefresh integrations › next-webpack5 › can hot reload context

    expect(received).toMatch(expected)

    Matcher error: received value must be a string

    Received has value: null

      314 |         const storeItems = await page.$('.store-items');
      315 |         let children = await storeItems.$$('li');
    > 316 |         expect(await getText(children[0])).toMatch('apple');
          |                                            ^
      317 | 
      318 |         await updateFile('src/context.jsx', content =>
      319 |           content.replace(

      at Object.<anonymous> (test/index.test.js:316:44)
          at runMicrotasks (<anonymous>)
```
</details>

Context
---

This is producing issues for me in a next JS preact prefresh project (private repo, otherwise I'd link) because I have code like:

```js
// ...
export const SOME_CONSTANT = 'some-string';
export const ANOTHER_CONSTANT_DERIVED_FROM_THE_FIRST_ONE = someTransformation(SOME_CONSTANT);
// ...
```

This is also—at least in theory—a problem for string-based components that get decorated by an HOC, where the HOC returns a string (not a function):

```js
// ...
const DecoratedComponent = someHocThatReturnsAString(BaseComponent);
export default DecoratedComponent;
```

Just to be clear by string-based components I mean something like:

```js
const Anchor = 'a';
// Which can be applied like any other component:
<Anchor />
```

I'm struggling to find React core documentation on this kind of thing, but it's sort of implied by:

> [The first argument to `React.createElement`]  can be either a tag name string (such as `'div'` or `'span'`), a React component type (a class or a function), or a React fragment type.

https://reactjs.org/docs/react-api.html#createelement

And:

> Types that start with a capital letter like `<Foo />` compile to `React.createElement(Foo)`

https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

I bring this up because I feel like this seems like a more encompassing / worst-case-y way to frame the problem. Capitalized vars that don't reference functions yes shouldn't brick the prefresh-consuming application; also string-based components should still properly trigger auto-refresh / hot-reload. This is what led me to build my [demo](https://github.com/ombene/prefresh/compare/main...demo-string-component-error) and [test case](https://github.com/ombene/prefresh/compare/main...373a4335db3d2f4eab4569862ccd0e8f19e9f480) around such an example.

**Comment by JoviDeCroock** [comment]
I agree that this is less than ideal but how do you suggest changing this heuristic? We could say that we don't register non-function components but that does mean that if we export this component and change it that it _might_ end up not-reloading components that import this.

**Comment by ombene** [comment]
Looks like you went for "we don't register non-function components" over in the fixing PR. And yeah that was my second thought (my first being turn the `WeakMap` into a `Map`), and definitely solves at least the problem I was having in my next JS project. Thank you so much!

I wanted to mention I tried that fix locally on the branch I've got with the added test case. It doesn't seem to resolve all the failing tests. Presumably not a big deal—I mean I'm not that familiar with this source code, my test case might be flimsy / improper. Regardless, I felt it was worth mentioning, for example in case it sparks some idea / realization on your end.

<details>
<summary>Results from that test run</summary>

```
 FAIL  test/index.test.js (246.016 s)
  Prefresh integrations
    vite
      ✓ basic component (1042 ms)
      ✓ add export (1007 ms)
      ✓ add file and import it (4014 ms)
      ✓ custom hook (2070 ms)
      ✓ resets hook state (1010 ms)
      ✓ re-runs changed effects (1013 ms)
      ✓ works for class-components (1034 ms)
      ✕ add a string-component file using a higher-order component (5107 ms)
      ✓ can change methods (1020 ms)
      ✓ can hot reload context (1053 ms)
    snowpack
      ✓ basic component (1030 ms)
      ✓ add export (1010 ms)
      ✓ add file and import it (4011 ms)
      ✓ custom hook (2056 ms)
      ✓ resets hook state (1008 ms)
      ✓ re-runs changed effects (1008 ms)
      ✓ works for class-components (1008 ms)
      ✕ add a string-component file using a higher-order component (5100 ms)
      ✕ can change methods (2070 ms)
      ✓ can hot reload context (1030 ms)
    nollup
      ✓ basic component (1034 ms)
      ✓ add export (1008 ms)
      ✓ add file and import it (4013 ms)
      ✓ custom hook (2062 ms)
      ✓ resets hook state (1007 ms)
      ✓ re-runs changed effects (1008 ms)
      ✓ works for class-components (1007 ms)
      ✓ add a string-component file using a higher-order component (4027 ms)
      ✓ can change methods (1097 ms)
      ✓ can hot reload context (1062 ms)
    next
      ✓ basic component (1012 ms)
      ✓ add export (1009 ms)
      ✓ add file and import it (4010 ms)
      ✓ custom hook (2051 ms)
      ✓ resets hook state (1007 ms)
      ✓ re-runs changed effects (1022 ms)
      ✓ works for class-components (1015 ms)
      ✓ add a string-component file using a higher-order component (4033 ms)
      ✓ can change methods (1057 ms)
      ✓ can hot reload context (1054 ms)
      ✓ can hot reload externally defined JSX (1016 ms)
    webpack
      ✓ basic component (1018 ms)
      ✓ add export (1010 ms)
      ✓ add file and import it (4019 ms)
      ✓ custom hook (2049 ms)
      ✓ resets hook state (1009 ms)
      ✓ re-runs changed effects (1012 ms)
      ✓ works for class-components (1011 ms)
      ✓ add a string-component file using a higher-order component (4017 ms)
      ✓ can change methods (1021 ms)
      ✓ can hot reload context (1049 ms)
      ✓ can hot reload externally defined JSX (1016 ms)
    web-dev-server
      ✓ basic component (1023 ms)
      ✓ add export (1012 ms)
      ✓ add file and import it (4018 ms)
      ✓ custom hook (2055 ms)
      ✓ resets hook state (1009 ms)
      ✓ re-runs changed effects (1009 ms)
      ✓ works for class-components (1012 ms)
      ✕ add a string-component file using a higher-order component (5075 ms)
      ✕ can change methods (2051 ms)
      ✓ can hot reload context (1037 ms)
    next-webpack5
      ✓ basic component (1011 ms)
      ✓ add export (1007 ms)
      ✓ custom hook (2066 ms)
      ✓ resets hook state (1009 ms)
      ✓ re-runs changed effects (1009 ms)
      ✓ works for class-components (1010 ms)
      ✕ add a string-component file using a higher-order component (3042 ms)
      ✓ can change methods (1021 ms)
      ✓ can hot reload context (1058 ms)

  ● Prefresh integrations › vite › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "DIV"
    Received string:    "SPAN"

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
      at Object.<anonymous> (test/index.test.js:288:9)

  ● Prefresh integrations › snowpack › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "DIV"
    Received string:    "SPAN"

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
      at Object.<anonymous> (test/index.test.js:288:9)

  ● Prefresh integrations › snowpack › can change methods

    expect(received).toMatch(expected)

    Expected substring: "hello"
    Received string:    "bye"

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
      at Object.<anonymous> (test/index.test.js:308:9)

  ● Prefresh integrations › web-dev-server › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "DIV"
    Received string:    "SPAN"

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/index.test.js:288:9)

  ● Prefresh integrations › web-dev-server › can change methods

    expect(received).toMatch(expected)

    Expected substring: "hello"
    Received string:    "bye"

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/index.test.js:308:9)

  ● Prefresh integrations › next-webpack5 › add a string-component file using a higher-order component

    expect(received).toMatch(expected)

    Expected substring: "SPAN"
    Received string:    ""

      16 |              const actual = (await poll()) || '';
      17 |              if (actual.indexOf(expected) > -1 || tries === maxTries - 1) {
    > 18 |                      expect(actual).toMatch(expected);
         |                                     ^
      19 |                      break;
      20 |              } else {
      21 |                      await timeout(50);

      at Object.<anonymous>.exports.expectByPolling (test/utils.js:18:19)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (test/index.test.js:281:9)
```
</details>
